---
- name: Gestión de software
  hosts: testservers
  become: yes

  tasks:
    - name: Verificar últimas versiones de paquetes
      ansible.builtin.dnf:
        name: "{{ item }}"
        state: latest
      loop:
        - bash
        - openssl
        - policycoreutils

    - name: Deshabilitar el repositorio epel
      ansible.builtin.yum_repository: 
        name: epel
        description: EPEL 9
        baseurl: https://dl.fedoraproject.org/pub/epel/9/Everything/$basearch # <-- ¡Añade esta línea!
        gpgkey: https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-9 # <-- Y esta también, si lo vas a definir como presente
        gpgcheck: yes # <-- Y esta
        enabled: no 
        state: present 

    - name: Eliminar repositorio EPEL
      ansible.builtin.yum_repository:
        name: epel
        state: absent 
    
    - name: Eliminar paquete htop que depende del repositorio EPEL 
      ansible.builtin.dnf: 
        name: htop 
        state: absent 