---
- name: Instalar Apache
  ansible.builtin.dnf:
    name: httpd
    state: present

- name: Desplegar página de inicio
  ansible.builtin.template:
    src: index.html.j2
    dest: /var/www/html/index.html
  notify: reiniciar apache

- name: Iniciar y habilitar servicio httpd
  ansible.builtin.service:
    name: httpd 
    state: started
    enabled: yes

