
---
- name: Example Playbook basic
  hosts: webservers
  gather_facts: true
  tasks:
    - name: Print a message
      ansible.builtin.debug:
        msg: "Hello, Ansible!"

    - name: Print another message
      ansible.builtin.debug:
        msg: "This is a simple playbook example."
# This playbook is a simple example that prints a message to the console
