#Ejercicio para crear un inventario
[dev]
dev-web.local
dev-db.local

[prod]
prod-web-01.local
prod-web-02.local

monitoring.example.com     #hosts que no pertenece a ningún grupo, bueno si, a un grupo especial *ungrouped*

[monitoring_servers]
monitoring.example.com     #un hosts puede pertenecer a varios grupos

[grupos_anidados:children] #un grupo puede pertenecer a otro grupo (anidado)
dev
prod


#comando ad-hoc para hacer ping a un grupo de host de un inventario específico. 
ansible prod -i inventory.ini -m ansible.builtin.ping 

