---
- name: Practica de condiciones
  hosts: webservers
  become: yes
  gather_facts: yes

  tasks: 
    - name: Enviar mensaje si se cumple la condiciÓN
      ansible.builtin.debug:
        msg: 
          - "Este servidor es físico '{{ ansible_virtualization_type }}'"
      when: ansible_virtualization_type == 'physical'
  