---
- name: Generar varias configuraciones 
  hosts: webservers
  become: yes

  tasks:
    - name: Instalar apache 
      ansible.builtin.dnf:
        name: httpd
        state: present

    - name: Crear directorio /srv/website
      ansible.builtin.file:
        path: /srv/website
        state: directory
        owner: apache

    - name: Copiar archivo app.js
      ansible.builtin.copy:
        src: index.html
        dest: /srv/website

    - name: Revisar si el paquete firewalld está desinstalado
      ansible.builtin.dnf:
        name: firewalld
        state: absent

