---
- name: Practicando con templates
  hosts: webservers
  become: yes

  tasks: 
    - name: Mostrar mensaje en el directorio /etc/issues
      ansible.builtin.template:
        src: tempplates/issue.j2
        dest: /etc/issues
        owner: root
        group: root 
        mode: '0644'

  