---
- name: Playbook para crear un usuario
  hosts: webservers
  become: yes
  vars:
    nombre_de_usuario: sysadmin

  tasks:
    - name: Crear usuario auditor
      ansible.builtin.user:
        name: "{{ nombre_de_usuario }}"
        state: present 
    
    - name: Mostrar mensaje de bienvenida
      ansible.builtin.debug:
        msg:
        - "El sistame operativo de este host es '{{ ansible_distribution }}'"
        