---
- name: Playbook para crear un usuario
  hosts: webservers
  become: yes
  vars:
    nombre_de_usuario: sysadmin

  tasks:
    - name: Crear usuario auditor
      ansible.builtin.user:
        name: " {{ nombre_de_usuario }}"
        state: present 
        